# Generated by Django 2.2 on 2021-08-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='Имя пользователя')),
                ('tg_id', models.PositiveIntegerField(verbose_name='id пользователя')),
                ('count_hotels', models.PositiveIntegerField(verbose_name='количество отелей')),
                ('destination_id', models.PositiveIntegerField(verbose_name='id города')),
                ('sort_order', models.CharField(max_length=128, verbose_name='порядок сортировки')),
                ('price_min', models.CharField(max_length=128, verbose_name='минимальная цена')),
                ('price_max', models.CharField(max_length=128, verbose_name='максимальная цена')),
                ('date_in', models.DateField(verbose_name='дата заезда')),
                ('date_out', models.DateField(verbose_name='дата выезда')),
            ],
        ),
    ]
