# Generated by Django 2.2 on 2021-08-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0002_auto_20210809_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauser',
            name='distance',
            field=models.FloatField(null=True, verbose_name='расстояние от цента'),
        ),
    ]
