# Generated by Django 2.2 on 2021-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0003_datauser_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='date_in',
            field=models.DateField(null=True, verbose_name='дата заезда'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='date_out',
            field=models.DateField(null=True, verbose_name='дата выезда'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='destination_id',
            field=models.PositiveIntegerField(null=True, verbose_name='id города'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='price_max',
            field=models.CharField(max_length=128, null=True, verbose_name='максимальная цена'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='price_min',
            field=models.CharField(max_length=128, null=True, verbose_name='минимальная цена'),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='sort_order',
            field=models.CharField(max_length=128, null=True, verbose_name='порядок сортировки'),
        ),
    ]
