# Generated by Django 2.2 on 2021-08-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0004_auto_20210810_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='count_hotels',
            field=models.PositiveIntegerField(null=True, verbose_name='количество отелей'),
        ),
    ]
