# Generated by Django 2.2 on 2021-08-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0006_auto_20210810_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='date_in',
            field=models.DateField(null=True, verbose_name='дата заезда'),
        ),
    ]
